### ISSUE TITLE
Erros on flutter 2

### ISSUE THREAD

**Issue by javierbm7** [peiffer-innovations/rest_client#3]
Failure with the new Flutter version

Resolving dependencies...
Because every version of rest_client depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0, rest_client is incompatible with flutter_localizations from sdk.
So, because oci_balance_app depends on both flutter_localizations any from sdk and rest_client ^1.0.6+2, version solving failed.
pub finished with exit code 1

**Comment by jpeiffer** [comment]
Should be fixed with the 2.0.0 that was released today.  That version includes the new null safety capabilities.  Please try again and let me know if you continue to have issues.
