### ISSUE TITLE
Handling with 'application/octet-stream'

### ISSUE THREAD

**Issue by sandjberd** [peiffer-innovations/rest_client#6]
Hi guys,

I want to fetch files from a REST api which returns a stream ('application/octet-stream'). I tried the following:

```
    var request = rc.Request(
        method: rc.RequestMethod.get,
        url: 'https://localhost:44324/api/someFileResource',
        headers: {
          'accept': 'application/octet-stream',
          'data': 'application/octet-stream',
          'content-type': 'application/octet-stream'
        });
```

```
    try {
      var response = await client.execute(
          request: request, authorizer: rc.TokenAuthorizer(token: token));
    } catch (e) {
      print(e.toString());
    }
```

Whenever I execute this, I get always the Restexception "Error from server: FormatException: Invalid UTF-8 byte (at offset 0)"

The REST API works with other applications, but not with my flutter.

Do you have any suggestions or any idea?

Many thanks in advance!

BR,

Sandj

**Comment by jpeiffer** [comment]
Thanks for the report.  Previously this was not possible.  I just released `2.1.0` which allows the functionality you're looking for.  Just do this:
```dart
    try {
      var response = await client.execute(
          jsonResponse: false, // add this line
          request: request, authorizer: rc.TokenAuthorizer(token: token));
    } catch (e) {
      print(e.toString());
    }
```
