### ISSUE TITLE
No way to send a request without the 'language' header

### ISSUE THREAD

**Issue by alexobviously** [peiffer-innovations/rest_client#7]
Just spent a while wondering why my API server was rejecting my requests, and it turns out it's because there's an unexpected header, 'language' being sent with the request.

This bit of code makes it impossible to not send the header:
```dart
if (!headers.containsKey('language')) {
      headers['language'] = Intl.defaultLocale ?? 'en_US';
    }
```

Of course I can set my server's CORS policy to accept this header, but that requires that I modify the CORS package I'm using for my backend, so It's kind of a pain. Moreover though, this could be breaking for people sending requests to APIs/services that they don't have control over.

(Also, I might be wrong but isn't the name of this header ['accept-language'](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)?)

**Comment by jpeiffer** [comment]
You are correct, it should have been `accept-language`.  Thanks for pointing that out.  :)

I fixed the name, and updated so you can unset any default header by setting it to empty.  Just update to:
```
rest_client: ^2.1.1
```
